### ISSUE TITLE
Share areas is not properly saved/reloaded on server restart

### ISSUE THREAD

**Issue by ghost** [SmallJoker/simple_protection#1]
Hi,

It seems that when you share an area with some other players, It's not saved. When the server restarts loose all the info about shared areas.

Thanks,

**Comment by SmallJoker** [comment]
https://github.com/SmallJoker/simple_protection/commit/890f#diff-b8910ad0c4225271ae285d16afbaeeefR132

Close the issue if it solved the problem.

**Comment by ghost** [comment]
Yes, it solves the problem. The mod is now the default protector mod in pixture server :)
Thankyou Krock!
