### ISSUE TITLE
Maximum number of claims

### ISSUE THREAD

**Issue by tacotexmex** [SmallJoker/simple_protection#11]
Being able to set a maximum number of claims per player will be immensely helpful agains hoarding. It could be called `s_protect.max_claims`.

**Comment by tacotexmex** [comment]
That was fast! Awesome. Is it possible to also have a setting that removes the oldest claims when making new ones too?

**Comment by SmallJoker** [comment]
No sorry, there are no timestamps saved in the area file. This means only claims that were created after adding that feature can be deleted.
EDIT: It would also increase the space usage of the database a lot, depending how big the world is and how many players there are.

**Comment by BrunoMine** [comment]
Besides all this. I must say that this limit is not very efficient. The player can use fake accounts for new claims and include them in them.

**Comment by tacotexmex** [comment]
Okay, I see. I'm looking for a simple claim mechanism where players can only have one claim at a time.

Fake accounts is a problem in all protection systems I guess. My players are goodhearted however, and I maintain a whitelist of users allowed.

**Comment by SmallJoker** [comment]
@BrunoMine Fake/multiple accounts are overall a problem on servers and out of scope of this mod. Limiting this by IP is nonsense, as there might be families/schools that would like to build in a world.
If the server owner still would like to limit the amount of accounts, then `names_by_ip` might be a possibility.

**Comment by BrunoMine** [comment]
If you really want to use a solution to this, it's through a system of levels of experience in the game, so a player with a fake account would need to play everything again to acquire the privileges, which would make this cheating model very unfeasible.

**Comment by tacotexmex** [comment]
Myself I don't care about cheating on my server, it's private, small with single accounts. Also cheating has nothing to do with this issue :)
