### ISSUE TITLE
Text-like map of surrounding areas

### ISSUE THREAD

**Issue by Fixer-007** [SmallJoker/simple_protection#15]
Seen this in MC towny mod, you type ```/towny map``` and it shows surrounding areas and their protection:
![cylfgqi](https://user-images.githubusercontent.com/16494741/27998144-47d16e24-6510-11e7-9cff-cb75a695e2d3.png)

Could be handy for this mod too.

**Comment by SmallJoker** [comment]
We don't have monospaced font in formspecs, thus this idea of a poor man's solution:
- Inventory buttons or plain images, at least 9x9 (we need a center for the current area)
- Name them, depending on claim state
- Where do we get colored text from?
- Prevent Android users from seeing this mess of buttons

Please keep in mind that Minetest worlds are quite higher and deeper, thus displaying those might be a bit more complicated. Perhaps something like the minimap in xray mode? Hopefully I somewhen get time for implementing this.

**Comment by SmallJoker** [comment]
Feedback please. e8339de

**Comment by BrunoMine** [comment]
It looks like it's working, but it's hard to understand which direction the map is turned on.
But perhaps you do not need much precision. Looks good.
It would be very useful an area larger than 9x9 (15x15 or 20x20)

**Comment by Fixer-007** [comment]
>It looks like it's working, but it's hard to understand which direction the map is turned on.

1. You should add:
- [x] N/E/W/S marks to the map (North added)
- [x] indication of other people claimed areas with different colour (three colours in total - not claimed/claimed by you/claimed by other players)
- [ ] coordinates for central block
- [x] indication of block where you stand (by adding some mark to it, or smth).
- [x] disclaimer about units used for squares
- [x] update Readme.txt
- [x] translations

**Comment by Fixer-007** [comment]
I pretty much like current implementation, if someone has more suggestions - please post it here.

**Comment by BrunoMine** [comment]
You can place a arrow for indicate the approximate player direction in the map center. Similar to compass operation

**Comment by Fixer-007** [comment]
also, "1 field = 1 area = blabla" is confusing, i would call it: "1 square = 1 area = blabla"

**Comment by SmallJoker** [comment]
@BrunoMine The compass mod uses 12 different images (and items) to show the rotation more or less precise. I would like to keep the data amount to a minimum and hope for a degree rotation texture modifier to do it like the minimap.
@Fixer-007 Renamed that one among other changes in 574ecb8

**Comment by BrunoMine** [comment]
@SmallJoker you do not need grandly increase data for this feature. Only 12 textures 8x8 is alright.
Maybe you can rotate the textures and reduce that number to 3

**Comment by SmallJoker** [comment]
Implemented 6 of the 7 requested features. The player marker from the minimap could be used to show the direction of the player more precisely. However, I'm quite happy how it turned out - a new issue could be opened if it lacks important features.
