### ISSUE TITLE
not all the commands / areas worm in the chat window

### ISSUE THREAD

**Issue by amadin** [SmallJoker/simple_protection#24]
![screenshot_20180801_090305](https://user-images.githubusercontent.com/13412191/43504416-0b48bd44-956c-11e8-81c5-2400f1e6a029.png)

"/ area show" for example did not fit

Game version 0.4.16 PC

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/6afbb06c7e552462ba2e682718488c9b13bfa0e5/minetest.conf.example#L783-L785

Set it to `7` or higher.
EDIT: Requires Minetest 5.0-dev.
