### ISSUE TITLE
Move files to a separate folder

### ISSUE THREAD

**Issue by amadin** [SmallJoker/simple_protection#26]
.

**Comment by SmallJoker** [comment]
Sorry, could you please be more precise about which files you're talking about?

**Comment by amadin** [comment]
I forgot to write, I mean the fashion files in the game folder \worlds\world _ name\. for example s_protect.conf, s_protect.data

**Comment by SmallJoker** [comment]
Where else should these be put? Example path?
The world directory is one of the few by mods writeable locations. I didn't check for subdirectories, but that might be a solution.
Meanwhile I only have 31 files in my most used development/testing world. Thus I don't think it's already necessary to separate the files. For simple_protection that's only three of them which all have the same prefix.
