### ISSUE TITLE
A bit confusing

### ISSUE THREAD

**Issue by ghost** [SmallJoker/simple_protection#29]
I hosted a local server and joined with two players from the same computer, the frist one named singleplayer1 (hoster), the second one named singleplayer2. 

I protected an area with singleplayer1, but singleplayer2 can dig and places nodes there and this player has only shout and interact as privilegs.

**Comment by SmallJoker** [comment]
Cannot reproduce. Are you sure that the area where you're interacting is protected? (`/area show`) 

If it is, please disable all other mods (temporary) and re-try. It might be caused by conflicting mods.

**Comment by ghost** [comment]
Yes I am sure, I always test mods with mtg vanilla first (forgot to wrote that, sorry).

**Comment by SmallJoker** [comment]
Please upload a minimally configured world so that I could try to reproduce it.

**Comment by ghost** [comment]
Ok it seems a bit different then I thought. 
I did more research. 
First: the protections **does** work. 

But there area several other issues I figured out. 
The command `/area show`, shows not "information about this area" as it is described, it just shows a 16x17x16 grid depending in wich direction you look at the moment you run that command and on wich y axis level you are. 

When you use the `simple_protection:claim` item on a node, it always claims the area like that: 
the node you clicked on is the left-lower corner when you facing north, no matter where you look at when you claim the area and the grid shows exactly that area, but correct only for the x and the z axis, cause that grid that also shows up while running that `/area show` command, shows a 16x17(yes seventeen)x16 grid, but the area is 16x150x16 for real (and not 16x80x16 as you wrote in your mod describtion). 
And these 150 nodes on the y axis are split into 100 nodes upwards from the node you click on and 49 nodes downwards from that node. 
Only the `/area radar` command helped me to show the correct position of the area and funny it also talks about the y axis and says that it is 150 blocks in height, but not how these 150 are distributed to +y and -y. 
Also the radar gui says "no claims on this Y level" even when I am inside the area. 
The screenshot that you ship with your mod seems to show that you clicked on that plant and thats the middle of the area, but that is not the case. 

--

This is all very confusing and I suggest the following: 
- Make it that the node you click on to claim an area, is the center of this area, this is an intuitive way of understanding the claim, that north-south axis thing is just confusing. 
- Make the area 17x17x17 per default, a mapblock is 16x16x16, the player always knows, that there are 8 nodes from that center node are protected in every direction and it is quite enough for a shed with some chests, a bed and a furnace. 
- The `/area show` can stay as it is, cause it is good to check if the claim will fit all nodes that the player wnats to claim, but it should take the players position as center and show always 17x17x17 nodes. 
- The `/area radar` command should show how the height is split and shouldn't say that theres no claim when there definitely is one. 

Oh and I've found a bug maybe: 
When you claim an area, place a `default:chest` inside of it, another player who has no rights can not open it when she or he has a node in hands, only with barehands or tools.

**Comment by ghost** [comment]
I would prefer an 16x16x16 area, because it is much more easier to indicate if a mapblock is loaded when you some nodes away (so furncae is active and so on). 
But for that you can not use the claimed node as the center for that area... 
So maybe keep that north-south axis orientation at claiming. 
I'm unsure it is your mod so your decision ;).

**Comment by SmallJoker** [comment]
> Make it that the node you click on to claim an area

I don't understand. It just claims the grid tile that contains the clicked node.

> I would prefer an 16x16x16 area, 

Change `s_protect.conf` within your world's directory to the following: `s_protect.claim_height = 16`
I won't change this because it's a nuisance to share areas like this (there's no bulk edit yet). If you need small areas, consider using `protector` which then also clobbers your lawn accordingly with protection nodes.

> it [area show] should take the players position as center and show always 17x17x17 nodes.

Would you mind explaining to me how this is supposed to work? The claim is padded to a grid, and it will always show the current area where the player stands in (i.e. feet position).

> The /area radar command should show how the height is split

Huh? This already happens by overlaying a `+` or `-` texture. For example, an area is above the current position:
![grafik](https://user-images.githubusercontent.com/1497498/113772351-e3b77500-9724-11eb-9c31-0d6448bedea6.png)

**Comment by ghost** [comment]
> I don't understand. It just claims the grid tile that contains the clicked node.

Node -> click on -> that node is the center of the area. 
But nevermind this point, I just get it how this "padded to a fix grid" thing works ;) 
But it would be good to display the correct height when run `/area show`, cause even with unlimeted view, I can't see the vertical beginning and end of it.

> > The /area radar command should show how the height is split
> Huh? This already happens by overlaying a `+` or `-` texture. For example, an area is above the current position:

It does not show how the exact data of the area height (from foo +y to bar -y). 
That icon thing forces people to climb up till the * is gone from radar gui and dig down till the minus is gone there too, running `/area radar` after every step, because as I said it is not consistent split the same amounts of nodes in both y directions and the radar just say it's 150m up/down. 


And what is it now with that `-> no claims on this Y level`? 
No matter where I stand (even in the exact node that I hit with the claim item) it always shows that text. 
You should change the screenshot, cause it suggests that you hit that plant and that this plant is now the middle of the area, that's the reason why I thought that it does not protect, cause I dug some node outside the real area.

**Comment by SmallJoker** [comment]
![grafik](https://user-images.githubusercontent.com/1497498/113901796-8298ab80-97cf-11eb-8452-38e418249eb1.png)

**Comment by SmallJoker** [comment]
![grafik](https://user-images.githubusercontent.com/1497498/113901888-96441200-97cf-11eb-8dfd-4e0d77dd787c.png)

I hope it's all clear now. Will check what's up with the right-click chest issue.
The screenshot is only a demo. Bad coincidence that it happens to be close to the center. This isn't `protector` and the mod description explains it very well too. Sorry, but I don't see any need to make this any clearer.

**Comment by SmallJoker** [comment]
Chest place issue fixed.

**Comment by ghost** [comment]
The default_settings.lua isn't loading by default, is this intented?

**Comment by SmallJoker** [comment]
https://github.com/SmallJoker/simple_protection/blob/3630fe92f10b7068ce84a83523dae1cc0e8a0487/init.lua#L21-L23

https://github.com/SmallJoker/simple_protection/blob/3630fe92f10b7068ce84a83523dae1cc0e8a0487/misc_functions.lua#L136-L138

**Comment by ghost** [comment]
Hmm.. it does not worked till i added a dofile line in init.lua
