### ISSUE TITLE
bug in the translation

### ISSUE THREAD

**Issue by BrunoMine** [SmallJoker/simple_protection#3]
I am getting several errors in the translated strings, I do not understand. Because you used `$` unlike using `@n`.

![bug_translation](https://cloud.githubusercontent.com/assets/7986261/17574550/932090f0-5f38-11e6-986a-1851e5da9057.jpg)
![bug_translation2](https://cloud.githubusercontent.com/assets/7986261/17574637/5c1b30be-5f39-11e6-9180-07942a964d61.jpg)

**Comment by SmallJoker** [comment]
> The dollar sign is reserved as placeholder to insert non-translated text

https://github.com/SmallJoker/simple_protection/blob/master/locale/template.txt#L1
This is equal to the `string.format` expression `%s`.

**Comment by BrunoMine** [comment]
You must use `@1`, `@2`, `@n` for it.

You did not explain how I can solve the problem. This has been corrected?

**Comment by SmallJoker** [comment]
The dollar sign `$` describes untranslated text -> nicknames.
Put the sign where usually the nickname would appear. The translations with `@1` and so on work as usual.
Keep a look at the german translation if you are not sure what I meant with that.

**Comment by BrunoMine** [comment]
The use of `@n` term can be used to concatenate any variable (including nicknames).

**Comment by SmallJoker** [comment]
Thank for pointing this out. No idea what I thought while adding the intllib support - somehow I assumed that the `@n` replacements are translated too, which is wrong.
I replaced that ugly dolar sign with the regular replacement markers now.
