### ISSUE TITLE
Can't Check if a Node is in Area Protected by Player Name

### ISSUE THREAD

**Issue by AntumDeluge** [SmallJoker/simple_protection#31]
https://github.com/SmallJoker/simple_protection/blob/3630fe92f10b7068ce84a83523dae1cc0e8a0487/protection.lua#L26

This always returns `false` (I think).

**Comment by SmallJoker** [comment]
Could you please explain what exactly your problem is? That function refers to the previous `minetest.is_protected` function to allow compatibility with other protection mods.

**Comment by AntumDeluge** [comment]
I'm trying to check if a player is the owner of an area. I only see two functions `s_protect.can_access(pos, player_name)` & `minetest.is_protected(pos, player_name)`. Maybe this is an engine bug?

**Edit:** Okay, just looked at the API. It looks like what I want to do is use `s_protect.get_claim(pos)`. I'll try that out.

**Edit:** Yes, that is what I wanted.
