### ISSUE TITLE
/area shareall command not working as intended

### ISSUE THREAD

**Issue by DemandingSloth** [SmallJoker/simple_protection#32]
when using /area shareall <user> with more than one person, only the last person has acces to the area.  i.e. player one uses share all to grant access to Player 2, Player 2 can now dig everywhere. Player one then subsequently ises share all to grant access to player 3. Player 3 can now dig normally and player 2 cannot. 

this behavior only happens with share all. this does not happen when using the share command on individual lots.

**Comment by SmallJoker** [comment]
Fixed in
https://github.com/SmallJoker/simple_protection/commit/5e7465ba#diff-13751f835bc7564c631cd01ca02fe1e9bee5377d3f75dfb56ca3f8a823f2ff18R177-L179

Please re-open (or ask to, if you cannot) this issue in case it still occurs with the newest master version.
