### ISSUE TITLE
List of areas

### ISSUE THREAD

**Issue by acmgit** [SmallJoker/simple_protection#36]
Is there a way, to list all areas with their boundaries of an owner in the chat or in a formspec?
This would be help to find areas outside of the radar-command.

Greetings,
Clyde.

**Comment by SmallJoker** [comment]
@acmgit Do you mean `/area list <playername>`? Use F10 / console view to have them lined up properly. Players listed after the `|` delimiter do have access to the area.

**Comment by acmgit** [comment]
Indeed, this is, what i thought, thanks for showing me. i must be blind ... ;-).
