### ISSUE TITLE
Add parameter "all" to command "unclaim"

### ISSUE THREAD

**Issue by SmallJoker** [SmallJoker/simple_protection#7]
Useful for server owners to unclaim all areas.

**Comment by SmallJoker** [comment]
1f3d919

@BrunoMine  There were additions in the translation file. Would be nice if you could update your language file somewhen aswell :)

**Comment by BrunoMine** [comment]
Yes, I will add on my list of tasks for the community.

**Comment by BrunoMine** [comment]
You have created the feature?
`/unclain all`?

**Comment by SmallJoker** [comment]
It was renamed to `/area delete <name>` but will do the same thing.
