### ISSUE TITLE
breaks tnt on entire world

### ISSUE THREAD

**Issue by ghost** [SmallJoker/simple_protection#9]
I add to minetest 4.14 dev then tnt will no longer damage nodes.

**Comment by SmallJoker** [comment]
Your issue title and description is not clear.
Could you please explain the situation and the problem

**Comment by ghost** [comment]
I create a world with default mods only and tnt will damage nodes when it explodes. After I add only simple_protection tnt will no longer damage nodes when it explodes.

**Comment by SmallJoker** [comment]
Fixed.
